enum ScreenNameEnum {
  //Auth Screens
  SPLASH_SCREEN = 'SPLASH_SCREEN',
  PaymentScreen='PaymentScreen',
  InvoiceScreen='InvoiceScreen',
  LOGIN_SCREEN = 'LOGIN_SCREEN',


  OTP_SCREEN = 'OTP_SCREEN',
  PROFILE_DETAILS = 'PROFILE_DETAILS',
  HOME_SCREEN = "HOME_SCREEN",
  BOTTAM_TAB = 'BOTTAM_TAB',
  ALL_SERVICES = 'ALL_SERVICES',
  BIKE_DETAILS = "BIKE_DETAILS",
  NEARBY_SHOPS = "NEARBY_SHOPS",
  GARAGE_DETAILS = "GARAGE_DETAILS",
  BOOKING_COMPLETE = "BOOKING_COMPLETE",
  BOOKING_SCREEN = 'BOOKING_SCREEN',
  SUPPORT_SCREEN = "SUPPORT_SCREEN",
  REWARD_SCREEN = 'REWARD_SCREEN',
  PROFILE_SCREEN = 'PROFILE_SCREEN',
  SERVICE_SUMMERY = 'SERVICE_SUMMERY',
  EDIT_PROFILE = 'EDIT_PROFILE',
  Notification ='Notification',
 
  VEHICAL_SCREEN = 'VEHICAL_SCREEN',
  NOTIFICATION_SETTING ="NOTIFICATION_SETTING",
  ABOUT_SCREEN ="ABOUT_SCREEN",
  PRIVACY_POLICY='PRIVACY_POLICY',
  SELECT_LOCATION ='SELECT_LOCATION',
  MY_BIKES='MY_BIKES',
  SupportForm='SupportForm',
  CHAT_SCREEN='CHAT_SCREEN',
  DEALER_WAITING='DEALER_WAITING',
  HELP_CENTER='HELP_CENTER',
  TICKET_LIST='TICKET_LIST',
  TERMS_CONDITIONS='TERMS_CONDITIONS',
  REFUND_POLICY='REFUND_POLICY',
  CANCELLATION_POLICY='CANCELLATION_POLICY',
  CONTACT_US='CONTACT_US',
  SOCIAL_LINKS='SOCIAL_LINKS',
  FAQ_SCREEN='FAQ_SCREEN',
  REWARDS_REFERRALS='REWARDS_REFERRALS',
  SERVICE_DETAIL='SERVICE_DETAIL',
  RATING_SCREEN='RATING_SCREEN',
  GARAGE_REVIEWS='GARAGE_REVIEWS',


}

export default ScreenNameEnum;
