import React, {useState} from 'react';
import {Image, ScrollView, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import MaterialCommunityIcons from 'react-native-vector-icons/MaterialCommunityIcons';
import ImagePicker from 'react-native-image-crop-picker';
import AsyncStorage from '@react-native-async-storage/async-storage';
import axios from 'axios';
import {base_url} from '../../redux/Api';
import {errorToast, successToast} from '../../configs/customToast';

const categories = [['mechanicBehaviour','Mechanic Behaviour'],['serviceQuality','Service Quality'],['pickupExperience','Pickup Experience'],['deliveryExperience','Delivery Experience'],['timeManagement','Time Management'],['communication','Communication'],['overallSatisfaction','Overall Satisfaction']] as const;
const Stars=({value,onChange,large=false}:{value:number;onChange:(n:number)=>void;large?:boolean})=><View style={styles.stars}>{[1,2,3,4,5].map(n=><TouchableOpacity key={n} onPress={()=>onChange(n)}><MaterialCommunityIcons name={n<=value?'star':'star-outline'} size={large?44:27} color={n<=value?'#FFD54A':'#555'}/></TouchableOpacity>)}</View>;

export default function RatingScreen({navigation,route}:any){
 const bookingId=route.params?.bookingId, existing=route.params?.review;
 const [rating,setRating]=useState(existing?.rating||0),[scores,setScores]=useState<Record<string,number>>(existing?.categoryRatings||{}),[comment,setComment]=useState(existing?.comment||''),[anonymous,setAnonymous]=useState(!!existing?.isAnonymous),[recommend,setRecommend]=useState<boolean|null>(existing?.recommend??null),[images,setImages]=useState<any[]>([]),[busy,setBusy]=useState(false);
 const pick=async()=>{try{const x=await ImagePicker.openPicker({multiple:true,maxFiles:5-images.length,mediaType:'photo',compressImageQuality:.75});setImages(p=>[...p,...(Array.isArray(x)?x:[x])].slice(0,5));}catch(e:any){if(e?.code!=='E_PICKER_CANCELLED')errorToast('Could not open photos.')}};
 const submit=async()=>{if(!rating)return errorToast('Choose an overall rating.');if(recommend===null)return errorToast('Please select YES or NO.');setBusy(true);try{const token=await AsyncStorage.getItem('token'),form=new FormData();form.append('booking_id',bookingId);form.append('rating',String(rating));form.append('comment',comment.trim());form.append('categoryRatings',JSON.stringify(scores));form.append('isAnonymous',String(anonymous));form.append('recommend',String(recommend));images.forEach((x,i)=>form.append('images',{uri:x.path,type:x.mime||'image/jpeg',name:x.filename||`review-${i}.jpg`} as any));await axios({method:existing?'PUT':'POST',url:`${base_url}/bikedoctor/rating/${existing?existing._id:'add'}`,data:form,headers:{token,'Content-Type':'multipart/form-data'}});successToast('Thank you for your feedback!');navigation.goBack();}catch(e:any){errorToast(e?.response?.data?.message||'Could not submit review.');}finally{setBusy(false)}};
 return <SafeAreaView style={styles.safe}><View style={styles.header}><TouchableOpacity onPress={navigation.goBack}><MaterialCommunityIcons name="arrow-left" size={25} color="#fff"/></TouchableOpacity><Text style={styles.headerTitle}>{existing?'Edit review':'Rate your service'}</Text><View style={{width:25}}/></View><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
  <View style={styles.hero}><Text style={styles.eyebrow}>MR BIKE DOCTOR</Text><Text style={styles.title}>{rating===5?'Absolutely amazing!':rating?'How was your experience?':'How was your experience?'}</Text><Text style={styles.sub}>Rate your overall service experience.</Text><Stars value={rating} onChange={setRating} large/><Text style={styles.hint}>{rating?`${rating} out of 5`:'Tap a star to rate'}</Text>{rating===5&&<Text style={styles.confetti}>🎉 ✨ 🎊</Text>}</View>
  <View style={styles.card}><Text style={styles.section}>Tell us more</Text>{categories.map(([key,label])=><View key={key} style={styles.category}><Text style={styles.label}>{label}</Text><Stars value={scores[key]||0} onChange={n=>setScores(s=>({...s,[key]:n}))}/></View>)}</View>
  <View style={styles.card}><View style={styles.row}><Text style={styles.section}>Share your thoughts</Text><Text style={styles.counter}>{comment.length}/1000</Text></View><TextInput value={comment} onChangeText={t=>setComment(t.slice(0,1000))} multiline placeholder="What stood out? Help other riders…" placeholderTextColor="#777" style={styles.input}/><Text style={styles.photoTitle}>Add photos <Text style={styles.optional}>Optional · up to 5</Text></Text><ScrollView horizontal><TouchableOpacity style={styles.addPhoto} onPress={pick}><MaterialCommunityIcons name="camera-plus-outline" size={25} color="#FFD54A"/><Text style={styles.addText}>Add photo</Text></TouchableOpacity>{images.map((x,i)=><View key={x.path} style={styles.photoWrap}><Image source={{uri:x.path}} style={styles.photo}/><TouchableOpacity style={styles.remove} onPress={()=>setImages(a=>a.filter((_,n)=>n!==i))}><MaterialCommunityIcons name="close" size={14} color="#fff"/></TouchableOpacity></View>)}</ScrollView></View>
  <View style={styles.card}><View style={styles.row}><View style={{flex:1}}><Text style={styles.label}>Post anonymously</Text><Text style={styles.muted}>Your identity won’t be displayed.</Text></View><Switch value={anonymous} onValueChange={setAnonymous}/></View><View style={styles.divider}/><Text style={styles.label}>Recommend MR Bike Doctor?</Text><View style={styles.choices}>{[true,false].map(v=><TouchableOpacity key={String(v)} style={[styles.choice,recommend===v&&styles.selected]} onPress={()=>setRecommend(v)}><Text style={[styles.choiceText,recommend===v&&{color:'#111'}]}>{v?'👍  YES':'👎  NO'}</Text></TouchableOpacity>)}</View></View>
  <TouchableOpacity disabled={!rating||busy} style={[styles.submit,(!rating||busy)&&{opacity:.45}]} onPress={submit}><Text style={styles.submitText}>{busy?'Submitting…':existing?'Update review':'Submit review'}</Text></TouchableOpacity><Text style={styles.privacy}>Only completed, invoiced and paid bookings can be reviewed.</Text>
 </ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#111'},header:{height:54,paddingHorizontal:18,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},headerTitle:{color:'#fff',fontWeight:'800',fontSize:16},content:{padding:16,paddingBottom:40},hero:{alignItems:'center',padding:25,backgroundColor:'#1B1B1B',borderRadius:22,borderWidth:1,borderColor:'#2D2D2D'},eyebrow:{color:'#FFD54A',fontSize:10,fontWeight:'900',letterSpacing:2},title:{fontSize:23,fontWeight:'900',color:'#fff',marginTop:10},sub:{fontSize:13,color:'#999',marginVertical:8},stars:{flexDirection:'row',gap:4},hint:{color:'#999',fontSize:12,marginTop:6},confetti:{fontSize:22,marginTop:5},card:{backgroundColor:'#1B1B1B',borderRadius:18,padding:16,borderWidth:1,borderColor:'#2B2B2B',marginTop:14},section:{color:'#fff',fontSize:17,fontWeight:'800',marginBottom:9},category:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingVertical:9,borderTopWidth:1,borderTopColor:'#292929'},label:{color:'#eee',fontSize:13,fontWeight:'700',flex:1},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},counter:{fontSize:11,color:'#888'},input:{minHeight:108,textAlignVertical:'top',backgroundColor:'#121212',borderRadius:13,borderWidth:1,borderColor:'#333',padding:13,color:'#fff'},photoTitle:{color:'#eee',fontWeight:'700',marginTop:16,marginBottom:9},optional:{color:'#777',fontWeight:'400'},addPhoto:{width:90,height:80,borderRadius:12,borderWidth:1,borderStyle:'dashed',borderColor:'#746328',alignItems:'center',justifyContent:'center',marginRight:9},addText:{color:'#FFD54A',fontSize:10,fontWeight:'700'},photoWrap:{marginRight:9},photo:{width:80,height:80,borderRadius:12},remove:{position:'absolute',right:4,top:4,backgroundColor:'#111c',borderRadius:12,padding:3},muted:{color:'#777',fontSize:11},divider:{height:1,backgroundColor:'#2B2B2B',marginVertical:15},choices:{flexDirection:'row',gap:10,marginTop:10},choice:{flex:1,height:44,borderRadius:11,borderWidth:1,borderColor:'#444',alignItems:'center',justifyContent:'center'},selected:{backgroundColor:'#FFD54A',borderColor:'#FFD54A'},choiceText:{color:'#ddd',fontWeight:'800'},submit:{height:54,borderRadius:15,backgroundColor:'#FFD54A',alignItems:'center',justifyContent:'center',marginTop:18},submitText:{fontWeight:'900',color:'#151515'},privacy:{color:'#666',fontSize:10,textAlign:'center',marginTop:9}});
